---
# tasks file for cache_python_mg
- name: Make sure that python-devel and gcc are installed
  zypper:
   name: "{{ item }}"
   state: "present"
  loop:
    - python-devel
    - gcc
  when: ansible_distribution is search("SUSE")
- name: Make sure that python-devel and gcc are installed
  yum:
   name: "{{ item }}"
   state: "present"
  loop:
    - python-devel
    - gcc
  when: ansible_distribution is not search("SUSE")
- name: clone the node service gateway git repo
  git:
    repo: https://github.com/chrisemunt/mg_python.git
    dest: /usr/local/mg_python
  tags:
    - skip_ansible_lint # Need to get latest version so ignoring need for version parameter
- name: copy Python test templates
  template:
     src: "{{ item.src }}"
     dest: "{{ item.dest }}"
     owner: root
     group: root
     mode: "{{ item.mode }}"
  loop:
     - { src: "templates/python-mg-test.py", dest: "/tmp/python-mg-test.py", mode: "0744" }
- name: Install the Python library
  command: python setup.py install
  args:
    chdir: /usr/local/mg_python/src
  register: outpt
  changed_when: outpt.stdout is not search("")
- name: Verify that the install is working as expected
  command: "/tmp/python-mg-test.py"
  register: outpt
  changed_when: outpt.stdout is not search("")
- name: Print whether the install has gone through or not
  debug: msg="mg-python for Intersystem Cache connectivity, has been installed correctly"
  when: outpt.stdout is search("The value of subscript 1 in the global Sample.PersonS in the SAMPLES namespace is 1")
- name: Print whether the install has gone through or not
  debug: msg="mg-pytnon for Intersystem Cache connectivity, has NOT been installed correctly"
  when: outpt.stdout is not search("The value of subscript 1 in the global Sample.PersonS in the SAMPLES namespace is 1")
